---
image: ghcr.io/esphome/esphome-lint:dev
ports:
  - port: 6052
    onOpen: open-browser
tasks:
  # yamllint disable-line rule:line-length
  - before: script/devcontainer-post-create
    command: python3 -m esphome dashboard config
