dependencies:
  esp-adf_audio_hal:
    git: https://github.com/espressif/esp-adf.git
    version: v2.5
    path: components/audio_hal
  esp-adf_audio_pipeline:
    git: https://github.com/espressif/esp-adf.git
    version: v2.5
    path: components/audio_pipeline
  esp-adf_audio_recorder:
    git: https://github.com/espressif/esp-adf.git
    version: v2.5
    path: components/audio_recorder
  esp-adf_audio_stream:
    git: https://github.com/espressif/esp-adf.git
    version: v2.5
    path: components/audio_stream
  esp-dsp:
    git: https://github.com/espressif/esp-dsp.git
    version: v1.2.0
  esp-tflite-micro:
    git: https://github.com/espressif/esp-tflite-micro.git
    version: v1.3.1
  esp32_camera:
    git: https://github.com/espressif/esp32-camera.git
    version: v2.0.9
  mdns:
    git: https://github.com/espressif/esp-protocols.git
    version: mdns-v1.2.5
    path: components/mdns
    rules:
      - if: "idf_version >=5.0"
